language: objective-c
os: osx
sudo: false

cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"

env:
  global:
    # $THEOS is absolutely needed for theos to even be found
    - THEOS=./theos

before_install:
  # set up theos
  - git clone --depth 1 --recursive https://github.com/theos/theos.git $THEOS
  - $THEOS/extras/ci/macos-setup.sh

script: make && make package

before_deploy: ls -la build

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "build/*.deb"
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
